-- cscope is currently unused; LSP provides the project navigation features.
-- require('cscope_maps').setup({
--   disable_maps = false,
--   skip_input_prompt = false,
--   prefix = "<leader>c",
--   cscope = {
--     db_file = "./cscope.out",
--     exec = "cscope",
--     picker = "telescope",
--     qf_window_size = 5,
--     qf_window_pos = "bottom",
--     skip_picker_for_single_result = true,
--     db_build_cmd = { args = { "-bqkv" } },
--     statusline_indicator = nil,
--     project_rooter = {
--       enable = true,
--       change_cwd = false,
--     },
--   },
-- })
